#!/usr/bin/env node
/**
 * script/export-abi.mjs
 *
 * Closes the gap flagged in Wave 4's dispatch: no typed ABI/bindings existed
 * anywhere for `apps/api`/`apps/keeper` TS code to import ProofLedger's ABI
 * from — every reference to it was a comment ("TODO: viem walletClient...").
 *
 * `forge build` already produces the full ABI as JSON under `out/` (gitignored
 * build artifact, regenerated every build — not safe to import from directly).
 * This script pulls it from there and writes two COMMITTED, human-diffable
 * outputs:
 *
 *   1. packages/contracts/exported/ProofLedger.abi.json
 *      Raw ABI JSON — same `exported/` convention as addresses.<network>.json
 *      (see exported/README.md), for any tool that wants plain JSON.
 *
 *   2. packages/sdk/src/abi/proof-ledger.ts
 *      A viem-ready `as const` TS literal — this is the one `apps/api` and
 *      `apps/keeper` actually import (via `@agentdesk/sdk`), since a plain
 *      `as const` array is what gives viem's `getContractEvents` /
 *      `readContract` / `writeContract` full argument/return type inference.
 *      packages/sdk is the existing shared seam (ARCHITECTURE.md §3 import
 *      rule: apps never import each other or reach into packages/contracts
 *      directly), so the ABI lives there alongside the zod schemas.
 *
 * Run via `pnpm --filter contracts export:abi` (also runs automatically as
 * part of `pnpm --filter contracts build`). Regenerate any time
 * ProofLedger.sol's external interface changes — IProofLedger.sol is frozen
 * per its own docstring, so in practice this only reruns when intentionally
 * versioning a new contract, never as a routine edit.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsRoot = join(here, "..");
const buildArtifactPath = join(
  contractsRoot,
  "out",
  "ProofLedger.sol",
  "ProofLedger.json",
);

let artifact;
try {
  artifact = JSON.parse(readFileSync(buildArtifactPath, "utf8"));
} catch (err) {
  console.error(
    `export-abi: could not read ${buildArtifactPath} — run \`forge build\` first.\n`,
    err.message,
  );
  process.exit(1);
}

const abi = artifact.abi;
if (!Array.isArray(abi) || abi.length === 0) {
  console.error("export-abi: build artifact had no usable `abi` array");
  process.exit(1);
}

// ── 1. exported/ProofLedger.abi.json (committed, plain JSON) ──────────────
const exportedDir = join(contractsRoot, "exported");
mkdirSync(exportedDir, { recursive: true });
const abiJsonPath = join(exportedDir, "ProofLedger.abi.json");
writeFileSync(abiJsonPath, `${JSON.stringify(abi, null, 2)}\n`);
console.log(`export-abi: wrote ${abiJsonPath}`);

// ── 2. packages/sdk/src/abi/proof-ledger.ts (committed, viem `as const`) ──
const sdkAbiDir = join(contractsRoot, "..", "sdk", "src", "abi");
mkdirSync(sdkAbiDir, { recursive: true });
const sdkAbiPath = join(sdkAbiDir, "proof-ledger.ts");

const banner = `/**
 * packages/sdk/src/abi/proof-ledger.ts
 *
 * GENERATED — do not hand-edit. Source of truth is
 * packages/contracts/src/ProofLedger.sol (via its frozen
 * src/interfaces/IProofLedger.sol), regenerated by
 * \`pnpm --filter contracts export:abi\` (packages/contracts/script/export-abi.mjs)
 * from \`forge build\`'s out/ProofLedger.sol/ProofLedger.json artifact.
 *
 * This is the ONLY place ProofLedger's ABI is defined for TS consumers —
 * apps/api and apps/keeper import \`proofLedgerAbi\` from '@agentdesk/sdk',
 * never from packages/contracts directly (ARCHITECTURE.md §3 import rule)
 * and never re-declare function signatures by hand. \`as const\` is load-
 * bearing: it's what lets viem's readContract/writeContract/getContractEvents
 * infer real argument and return types from this array instead of \`any\`.
 *
 * Regenerate after any ProofLedger.sol interface change — IProofLedger.sol's
 * own docstring freezes it (a breaking change is a new contract version, not
 * an edit), so in practice this stays stable.
 */
export const proofLedgerAbi = ${JSON.stringify(abi, null, 2)} as const;
`;

writeFileSync(sdkAbiPath, banner);
console.log(`export-abi: wrote ${sdkAbiPath}`);
