/*
 * Mock marketplace data — the 13 demo agents from docs/PROTOTYPE-PROMPT.md.
 * One clearly-named file with a typed interface so it can be swapped for the
 * packages/sdk fixture client (A0.3) and the real API (B1.1) later.
 */

export type Category = 'grid' | 'rebalancing' | 'yield' | 'health'
export type Risk = 'Low' | 'Medium' | 'High'

export interface Agent {
  id: string
  name: string
  tagline: string
  category: Category
  /** verified 30d return in percent — null until the first on-chain proof lands */
  return30d: number | null
  winRate: number | null
  tasks: number | null
  risk: Risk
  pricePerTask: number
  protocol: string
  verified: boolean
  /** average minutes from pre-registered intent to execution */
  respMinutes: number
  listedDaysAgo: number
  spark: number[]
}

export const CATEGORY_LABELS: Record<Category, string> = {
  grid: 'Grid',
  rebalancing: 'Rebalancing',
  yield: 'Yield',
  health: 'Health Guard',
}

export const AGENTS: Agent[] = [
  {
    id: 'gridgoblin',
    name: 'GridGoblin',
    tagline: 'Grids CAKE/USDT while you sleep',
    category: 'grid',
    return30d: 31.4,
    winRate: 82,
    tasks: 1204,
    risk: 'Medium',
    pricePerTask: 0.8,
    protocol: 'PancakeSwap',
    verified: true,
    respMinutes: 3.8,
    listedDaysAgo: 120,
    spark: [2, 2.6, 2.3, 3.1, 3.6, 3.3, 4.2, 4.8, 4.5, 5.4, 6, 6.3],
  },
  {
    id: 'gridmind',
    name: 'GridMind',
    tagline: 'Adaptive grid bands with volatility brakes',
    category: 'grid',
    return30d: 18.2,
    winRate: 76,
    tasks: 842,
    risk: 'Low',
    pricePerTask: 1.2,
    protocol: 'PancakeSwap',
    verified: true,
    respMinutes: 2.6,
    listedDaysAgo: 64,
    spark: [2, 2.3, 2.5, 2.4, 2.8, 3, 2.9, 3.3, 3.5, 3.6, 3.8],
  },
  {
    id: 'gridrunner',
    name: 'GridRunner',
    tagline: 'High-frequency micro-grids on memecoins',
    category: 'grid',
    return30d: 54.9,
    winRate: 61,
    tasks: 3118,
    risk: 'High',
    pricePerTask: 0.4,
    protocol: 'PancakeSwap',
    verified: true,
    respMinutes: 1.2,
    listedDaysAgo: 12,
    spark: [2, 3.2, 2.4, 4, 3.1, 5, 3.8, 5.6, 4.6, 6.4, 5.5, 7.2],
  },
  {
    id: 'rangeranger',
    name: 'RangeRanger',
    tagline: 'Keeps your PancakeSwap v3 range centered',
    category: 'rebalancing',
    return30d: 12.7,
    winRate: 88,
    tasks: 611,
    risk: 'Low',
    pricePerTask: 1.5,
    protocol: 'PancakeSwap v3',
    verified: true,
    respMinutes: 4.4,
    listedDaysAgo: 200,
    spark: [2, 2.2, 2.5, 2.4, 2.7, 2.9, 2.8, 3.1, 3.3, 3.2, 3.5],
  },
  {
    id: 'rangebot-prime',
    name: 'RangeBot Prime',
    tagline: 'Auto re-centers LP on volatility bursts',
    category: 'rebalancing',
    return30d: 9.3,
    winRate: 91,
    tasks: 489,
    risk: 'Low',
    pricePerTask: 2.0,
    protocol: 'PancakeSwap v3',
    verified: true,
    respMinutes: 5.1,
    listedDaysAgo: 95,
    spark: [2, 2.1, 2.3, 2.4, 2.5, 2.7, 2.8, 2.8, 3, 3.1],
  },
  {
    id: 'fluxrange',
    name: 'FluxRange',
    tagline: 'Wide-range LP optimizer for lazy liquidity',
    category: 'rebalancing',
    return30d: 6.1,
    winRate: 84,
    tasks: 233,
    risk: 'Low',
    pricePerTask: 0.9,
    protocol: 'PancakeSwap v3',
    verified: true,
    respMinutes: 3.2,
    listedDaysAgo: 30,
    spark: [2, 2.4, 2.2, 2.6, 2.5, 2.8, 2.7, 3, 2.9, 3.2],
  },
  {
    id: 'yieldshepherd',
    name: 'YieldShepherd',
    tagline: 'Moves funds to where APY actually is',
    category: 'yield',
    return30d: 14.8,
    winRate: 93,
    tasks: 1042,
    risk: 'Low',
    pricePerTask: 0.6,
    protocol: 'Farms',
    verified: true,
    respMinutes: 2.9,
    listedDaysAgo: 180,
    spark: [2, 2.3, 2.6, 2.5, 2.9, 3.1, 3, 3.4, 3.6, 3.8],
  },
  {
    id: 'farmhand',
    name: 'FarmHand',
    tagline: 'Conservative farm rotation, weekly harvests',
    category: 'yield',
    return30d: 8.4,
    winRate: 95,
    tasks: 512,
    risk: 'Low',
    pricePerTask: 0.5,
    protocol: 'Farms',
    verified: true,
    respMinutes: 6.3,
    listedDaysAgo: 150,
    spark: [2, 2.15, 2.3, 2.45, 2.4, 2.6, 2.75, 2.7, 2.9, 3],
  },
  {
    id: 'alphayield',
    name: 'AlphaYield',
    tagline: 'Chases hot farms, cuts fast when they die',
    category: 'yield',
    return30d: 38.9,
    winRate: 67,
    tasks: 1877,
    risk: 'High',
    pricePerTask: 1.1,
    protocol: 'Farms',
    verified: true,
    respMinutes: 1.8,
    listedDaysAgo: 45,
    spark: [2, 2.8, 2.2, 3.6, 2.7, 4.2, 3.2, 4.8, 3.9, 5.6],
  },
  {
    id: 'healthguard',
    name: 'HealthGuard',
    tagline: 'Stops your Venus loan from liquidating',
    category: 'health',
    return30d: 2.1,
    winRate: 99,
    tasks: 96,
    risk: 'Low',
    pricePerTask: 1.0,
    protocol: 'Venus',
    verified: true,
    respMinutes: 7.2,
    listedDaysAgo: 220,
    spark: [2, 2.05, 2.1, 2.02, 2.14, 2.1, 2.2, 2.16, 2.26, 2.3],
  },
  {
    id: 'guardianv2',
    name: 'GuardianV2',
    tagline: 'Aave + Venus collateral sniper',
    category: 'health',
    return30d: 1.7,
    winRate: 98,
    tasks: 74,
    risk: 'Low',
    pricePerTask: 1.3,
    protocol: 'Aave + Venus',
    verified: true,
    respMinutes: 8,
    listedDaysAgo: 60,
    spark: [2, 2.02, 2.06, 2, 2.08, 2.05, 2.12, 2.1, 2.16, 2.18],
  },
  {
    id: 'moonmechanic',
    name: 'MoonMechanic',
    tagline: 'Fresh agent, first proofs landing soon',
    category: 'grid',
    return30d: null,
    winRate: null,
    tasks: null,
    risk: 'Medium',
    pricePerTask: 0.3,
    protocol: 'PancakeSwap',
    verified: false,
    respMinutes: 2.2,
    listedDaysAgo: 2,
    spark: [2, 2, 2.05, 2, 2, 2.04, 2, 2, 2.02, 2],
  },
  {
    id: 'yieldpilot',
    name: 'YieldPilot',
    tagline: 'Scouts new farms before they trend',
    category: 'yield',
    return30d: null,
    winRate: null,
    tasks: null,
    risk: 'Low',
    pricePerTask: 0.45,
    protocol: 'Farms',
    verified: false,
    respMinutes: 3.5,
    listedDaysAgo: 1,
    spark: [2, 2, 2.03, 2, 2, 2.02, 2, 2, 2.01, 2],
  },
]
