/**
 * apps/api/src/services/altana.ts
 *
 * Altana integration — agent-owned wallets, scoped sessions, public Keystore,
 * `hireErc8183Agent`, in-product revocation (INTEGRATION.md I6). This is the
 * ONLY place that should call the Altana SDK. CLAUDE.md rule 1: we do not
 * build our own session/escrow logic — we call Altana's.
 *
 * LIVE (2026-08-17): @altananetwork/sdk is real, published, self-custodial —
 * NO API key / hosted backend required (corrected from the earlier
 * "hackathon-gated" assumption; see INTEGRATION.md I6/I14). Every function
 * below calls the real SDK against BSC Chapel testnet (BNB_TESTNET, chain
 * 97) using the bootstrap agent wallet from ALTANA_WALLET_PRIVATE_KEY
 * (apps/api/.env.altana-agent, gitignored — generated by
 * scripts/altana-live-proof.ts, mirrors DEMO_AGENT_PRIVATE_KEY's pattern).
 *
 * PROVEN ON-CHAIN this wave (see final report / INTEGRATION.md I6 for tx
 * hashes): real wallet creation, real tBNB funding, a real KeyStore-
 * registered grantSession (11 event logs, EIP-7702 delegation confirmed).
 * The execute()-through-session step was root-caused (wrong ABI type for
 * ProofLedger's `deadline` — uint64, not uint256 — silently produces the
 * wrong 4-byte selector) and fixed here and in the proof script, but a full
 * fresh end-to-end run was blocked by deployer testnet-gas exhaustion, not
 * by anything in this code — see final report.
 *
 * UPDATED (2026-08-17, hire.ts real wiring): createAgentWallet() now lets a
 * caller (services/hire.ts's createJob()) provision a FRESH real Altana
 * wallet per job, funded from the Chapel deployer key and granted its own
 * scoped session — see hire.ts for the full per-job flow. This does not
 * replace the bootstrap wallet (still the default when createScopedSession
 * is called without an explicit wallet/signer) — both paths coexist.
 *
 * KNOWN LIMITATION (flagged, not hidden, still applies to fresh per-job
 * wallets too): granted sessions are cached in-process (Map, now keyed
 * wallet+signer+session together — see liveSessions banner below), not
 * persisted to Postgres — a restart loses the ability to revoke/execute
 * through a live session by id (the raw session/signer key material is
 * deliberately never written to the `sessions` table — only public
 * metadata is). A real one-wallet-per-marketplace-agent *registry* (reusing
 * the same wallet across a given agent's repeat hires, rather than minting
 * a new one per job) is still a real follow-up, not a silent gap.
 *
 * hireErc8183Agent() is wired to the real SDK call but still needs one live
 * acceptance run with (a) a willing seller/provider address and (b) a fresh
 * buyer wallet holding tBNB and $U. `$U` is self-serve on Chapel as of
 * 2026-08-19 via https://united-coin-u.github.io/u-faucet/; the prior
 * no-faucet conclusion was stale. The remaining work is integration and
 * deploy-safe wallet funding, not payment-token access.
 */
import {
  buildHireCalls,
  ERC8183_ADDRESSES,
  erc8183Addresses,
  getErc8183Job,
  hireErc8183Agent as sdkHireErc8183Agent,
  signerFromPrivateKey,
  type Session as AltanaSession,
  type Signer as AltanaSigner,
  type Wallet as AltanaWallet,
} from '@altananetwork/sdk'
import { randomUUID } from 'node:crypto'
import type { Address, Hex } from 'viem'
import { generatePrivateKey } from 'viem/accounts'
import { parseUnits } from 'viem'
import { BNB_TESTNET, getAltanaClient, getAltanaWallet, getAltanaWalletSigner } from '../lib/altana-client.js'
import { getProofLedgerAddress } from '../lib/chain.js'
import { logger } from '../logger.js'
import type { Session } from '../types/domain.js'

export interface CreateScopedSessionInput {
  agentId: string
  jobId: string
  ownerAddress: string
  allowlist: string[]
  spendCapUsd1: number
  durationDays: number
  /**
   * The Altana wallet/signer this session is granted on. Defaults to the
   * bootstrap wallet (ALTANA_WALLET_ADDRESS/PRIVATE_KEY) when omitted — pass
   * a fresh per-job wallet (see createAgentWallet()) for a genuinely
   * agent-owned, per-hire wallet instead of reusing the one bootstrap
   * wallet for every job.
   */
  wallet?: AltanaWallet
  signer?: AltanaSigner
}

export interface FreshAgentWallet {
  address: Address
  /** NEVER log/print this — caller persists it to a gitignored per-job env file (mirrors .env.altana-agent's pattern). */
  privateKey: Hex
  signer: AltanaSigner
  wallet: AltanaWallet
}

/**
 * Generates a fresh, self-custodial Altana wallet (a NEW private key,
 * distinct from the bootstrap ALTANA_WALLET_PRIVATE_KEY) — same mechanism
 * scripts/altana-live-proof.ts uses. Counterfactual only (no on-chain tx) —
 * the caller must fund the address before granting a session on it.
 */
export async function createAgentWallet(): Promise<FreshAgentWallet> {
  const privateKey = generatePrivateKey()
  const signer = signerFromPrivateKey(privateKey)
  const client = getAltanaClient()
  const result = await client.createWallet({ signer })
  logger.info({ address: result.address }, 'altana: fresh agent wallet created (counterfactual)')
  return { address: result.address, privateKey, signer, wallet: result }
}

/**
 * Granted Altana sessions, keyed by OUR session id. Process-local cache —
 * see file header "KNOWN LIMITATION". Holds the real SDK Session object
 * (needed by hireErc8183Agent()'s session-path overload) PLUS the wallet +
 * admin signer that granted it (needed by revokeSession() — Altana's
 * `client.revokeSession` is signed by the wallet's admin authority, not the
 * session's own key, so this must be the SAME wallet/signer used at grant
 * time — critical now that createJob() grants each job its own fresh
 * wallet rather than always reusing the one bootstrap wallet).
 */
const liveSessions = new Map<string, { session: AltanaSession; wallet: AltanaWallet; signer: AltanaSigner }>()

/** Either a signature-scoped call, or (for the ERC-8183 hire batch, which touches several selectors on two contracts) a whole-contract grant — still a real, named, non-wildcard-across-contracts scope, never "allow everything". */
type BuiltCallPermission = { to: Address; signature: string } | { to: Address }

/**
 * Maps our allowlist strings to real Altana CallPermission entries. Only
 * recognized entries are honored — an unrecognized entry is a hard error
 * (deny-by-default), never silently widened to "allow all calls" (that
 * would be the opposite of a scoped session).
 */
function buildCallPermissions(allowlist: string[]): BuiltCallPermission[] {
  const permissions: BuiltCallPermission[] = []
  for (const entry of allowlist) {
    if (entry === 'ProofLedger.registerDecision') {
      permissions.push({
        to: getProofLedgerAddress(),
        signature: 'registerDecision(uint256,bytes32,uint64)',
      })
      continue
    }
    if (entry === 'Erc8183.hire') {
      // hireErc8183Agent's real 5-call batch (createJob, registerJob,
      // setBudget, approve $U, fund — see @altananetwork/sdk's
      // buildHireCalls) touches several selectors across two contracts, so
      // this grants whole-contract scope on exactly those two addresses
      // (still a named, bounded grant — not "allow everything"), rather
      // than hand-maintaining every selector here.
      const addresses = erc8183Addresses(BNB_TESTNET.chainId)
      permissions.push({ to: addresses.commerce }, { to: addresses.paymentToken })
      continue
    }
    throw new Error(
      `altana.createScopedSession: unrecognized allowlist entry "${entry}" — refusing to grant an unscoped session`,
    )
  }
  return permissions
}

export async function createScopedSession(input: CreateScopedSessionInput): Promise<Session> {
  const client = getAltanaClient()
  const wallet = input.wallet ?? getAltanaWallet()
  const signer = input.signer ?? getAltanaWalletSigner()

  const expirySeconds = Math.floor(Date.now() / 1000) + input.durationDays * 24 * 60 * 60
  const callPermissions = buildCallPermissions(input.allowlist)

  // Spend cap in $U (United Stables) — the real ERC-8183 payment token on
  // BNB Testnet (INTEGRATION.md I6/I14), 18 decimals, confirmed live via a
  // direct chain read (name="United Stables", symbol="U").
  const paymentToken = erc8183Addresses(BNB_TESTNET.chainId).paymentToken

  const grant = await client.grantSession({
    wallet,
    signer,
    permissions: {
      calls: callPermissions,
      spend: [{ limit: parseUnits(input.spendCapUsd1.toString(), 18), period: 'day', token: paymentToken }],
    },
    expiry: expirySeconds,
    register: true, // full public KeyStore registration — Altana-track checklist item
    chainId: BNB_TESTNET.chainId,
  })

  const sessionId = `altana_${randomUUID()}`
  liveSessions.set(sessionId, { session: grant, wallet, signer })

  logger.info(
    { sessionId, walletAddress: grant.walletAddress, expiry: expirySeconds, tx: grant.transactionHash },
    'altana: real scoped session granted (KeyStore-registered)',
  )

  return {
    id: sessionId,
    jobId: input.jobId,
    agentId: input.agentId,
    allowlist: input.allowlist,
    spendCapUsd1: input.spendCapUsd1,
    expiresAt: new Date(expirySeconds * 1000).toISOString(),
    revokedAt: null,
    keystoreTx: grant.transactionHash ?? null,
  }
}

export interface HireErc8183Result {
  escrowRef: string
  fundedTx: string | null
}

export interface HireErc8183Params {
  /** Real ERC-8004-registered seller/provider address — never fabricated. */
  provider: Address
  task: string
  /** Budget in $U (United Stables), human units (e.g. 5 = 5 $U). */
  budgetUsd1: number
  deadlineSeconds?: number
}

/**
 * Altana's ERC-8183 hiring helper — Altana-track bonus criterion. Wired to
 * the real SDK call. See file header: genuinely untested live this wave —
 * needs a real `provider` counterparty and $U balance, neither fabricated.
 * Callers MUST supply a real, already-known provider address; this
 * function does not invent one.
 */
export async function hireErc8183Agent(
  sessionId: string,
  params: HireErc8183Params,
): Promise<HireErc8183Result | null> {
  const entry = liveSessions.get(sessionId)
  if (!entry) {
    logger.warn({ sessionId }, 'altana.hireErc8183Agent: no live session for id — refusing')
    return null
  }
  const result = await sdkHireErc8183Agent(
    entry.session,
    { provider: params.provider, task: params.task, budget: parseUnits(params.budgetUsd1.toString(), 18) },
    { network: BNB_TESTNET },
  )
  return {
    escrowRef: result.jobId.toString(),
    fundedTx: result.transactionHash ?? null,
  }
}

export async function revokeSession(
  sessionId: string,
): Promise<{ revokedAt: string; tx: string | null } | null> {
  const entry = liveSessions.get(sessionId)
  if (!entry) {
    logger.warn({ sessionId }, 'altana.revokeSession: no live session for id')
    return null
  }
  const client = getAltanaClient()
  // MUST be the same wallet+signer that granted this session (Altana's
  // revokeSession is authorized by the wallet's admin authority, not the
  // session's own key) — never the fixed bootstrap wallet when this session
  // was granted on a fresh per-job wallet (see liveSessions banner above).
  const { session, wallet, signer } = entry

  const result = await client.revokeSession({ wallet, signer, session, chainId: BNB_TESTNET.chainId })
  // Deliberately NOT deleted from liveSessions (changed 2026-08-17) — mirrors
  // the Postgres pattern (sessions.revoked_at is set, the row is never
  // deleted): keeping the entry lets a subsequent call attempt actually
  // reach the SDK/relay again and get a REAL on-chain/relay-level refusal
  // (the only thing that actually enforces revocation), instead of merely
  // failing our own local "is it in the Map" check — a strictly weaker,
  // less honest proof of revocation working.
  liveSessions.set(sessionId, entry)

  logger.info({ sessionId, tx: result.transactionHash }, 'altana: real session revoked on-chain')

  return { revokedAt: new Date().toISOString(), tx: result.transactionHash ?? null }
}

/**
 * Plain-language Trust Panel sentence from an actual session config — never
 * from anything other than the session object itself (no paraphrasing of
 * agent-reported claims).
 */
export function permissionSentence(
  session: Pick<Session, 'allowlist' | 'spendCapUsd1' | 'expiresAt'>,
): string {
  const scope = session.allowlist.length > 0 ? session.allowlist.join(', ') : 'nothing yet'
  const expiry = new Date(session.expiresAt).toLocaleDateString()
  return `Can trade ${scope}, up to $${session.spendCapUsd1.toFixed(2)}/day, until ${expiry}.`
}

// Re-exported for callers that want to read job state directly (e.g. a
// future job-status poller) without duplicating SDK imports.
export { ERC8183_ADDRESSES, buildHireCalls, getErc8183Job }
