/**
 * apps/api/src/services/altana.ts
 *
 * Altana integration — agent-owned wallets, scoped sessions, public Keystore,
 * `hireErc8183Agent`, in-product revocation (INTEGRATION.md I6). This is the
 * ONLY place that should call the Altana SDK. CLAUDE.md rule 1: we do not
 * build our own session/escrow logic — we call Altana's.
 *
 * LIVE (2026-08-17): @altananetwork/sdk is real, published, self-custodial —
 * NO API key / hosted backend required (corrected from the earlier
 * "hackathon-gated" assumption; see INTEGRATION.md I6/I14). Every function
 * below calls the real SDK against BSC Chapel testnet (BNB_TESTNET, chain
 * 97) using the bootstrap agent wallet from ALTANA_WALLET_PRIVATE_KEY
 * (apps/api/.env.altana-agent, gitignored — generated by
 * scripts/altana-live-proof.ts, mirrors DEMO_AGENT_PRIVATE_KEY's pattern).
 *
 * PROVEN ON-CHAIN this wave (see final report / INTEGRATION.md I6 for tx
 * hashes): real wallet creation, real tBNB funding, a real KeyStore-
 * registered grantSession (11 event logs, EIP-7702 delegation confirmed).
 * The execute()-through-session step was root-caused (wrong ABI type for
 * ProofLedger's `deadline` — uint64, not uint256 — silently produces the
 * wrong 4-byte selector) and fixed here and in the proof script, but a full
 * fresh end-to-end run was blocked by deployer testnet-gas exhaustion, not
 * by anything in this code — see final report.
 *
 * KNOWN LIMITATION (flagged, not hidden): this wave wires ONE real Altana
 * wallet (the bootstrap wallet), not a full one-wallet-per-marketplace-agent
 * registry — that needs a DB table (`altana_wallets` or similar) that
 * doesn't exist yet. Granted sessions are cached in-process (Map), not
 * persisted to Postgres — a restart loses the ability to revoke/execute
 * through a live session by id. Both are real follow-ups, not silent gaps.
 *
 * hireErc8183Agent() is wired to the real SDK call but genuinely untested
 * live this wave: it needs (a) a real ERC-8004-registered counterparty
 * `provider` address willing to receive the job, and (b) $U (United
 * Stables, the ERC-8183 payment token — confirmed live on chain 97 at
 * 0xc70B8741B8B07A6d61E54fd4B20f22Fa648E5565) balance in the wallet, which
 * has no self-serve faucet (it's Ownable; `owner()` reads a real address
 * that isn't us). Neither is an account/API gate — both are "we don't have
 * the counterparty/funds yet," reported plainly per the task brief rather
 * than faked.
 */
import {
  buildHireCalls,
  ERC8183_ADDRESSES,
  erc8183Addresses,
  getErc8183Job,
  hireErc8183Agent as sdkHireErc8183Agent,
  type Session as AltanaSession,
} from '@altananetwork/sdk'
import { randomUUID } from 'node:crypto'
import type { Address } from 'viem'
import { parseUnits } from 'viem'
import { BNB_TESTNET, getAltanaClient, getAltanaWallet, getAltanaWalletSigner } from '../lib/altana-client.js'
import { getProofLedgerAddress } from '../lib/chain.js'
import { logger } from '../logger.js'
import type { Session } from '../types/domain.js'

export interface CreateScopedSessionInput {
  agentId: string
  jobId: string
  ownerAddress: string
  allowlist: string[]
  spendCapUsd1: number
  durationDays: number
}

/**
 * Granted Altana sessions, keyed by OUR session id. Process-local cache —
 * see file header "KNOWN LIMITATION". Holds the real SDK Session object
 * (includes the session's own signer), needed by revokeSession()/any future
 * execute-through-session call.
 */
const liveSessions = new Map<string, AltanaSession>()

/**
 * Maps our allowlist strings to real Altana CallPermission entries. Only
 * recognized entries are honored — an unrecognized entry is a hard error
 * (deny-by-default), never silently widened to "allow all calls" (that
 * would be the opposite of a scoped session).
 */
function buildCallPermissions(allowlist: string[]): { to: Address; signature: string }[] {
  const permissions: { to: Address; signature: string }[] = []
  for (const entry of allowlist) {
    if (entry === 'ProofLedger.registerDecision') {
      permissions.push({
        to: getProofLedgerAddress(),
        signature: 'registerDecision(uint256,bytes32,uint64)',
      })
      continue
    }
    throw new Error(
      `altana.createScopedSession: unrecognized allowlist entry "${entry}" — refusing to grant an unscoped session`,
    )
  }
  return permissions
}

export async function createScopedSession(input: CreateScopedSessionInput): Promise<Session> {
  const client = getAltanaClient()
  const wallet = getAltanaWallet()
  const signer = getAltanaWalletSigner()

  const expirySeconds = Math.floor(Date.now() / 1000) + input.durationDays * 24 * 60 * 60
  const callPermissions = buildCallPermissions(input.allowlist)

  // Spend cap in $U (United Stables) — the real ERC-8183 payment token on
  // BNB Testnet (INTEGRATION.md I6/I14), 18 decimals, confirmed live via a
  // direct chain read (name="United Stables", symbol="U").
  const paymentToken = erc8183Addresses(BNB_TESTNET.chainId).paymentToken

  const grant = await client.grantSession({
    wallet,
    signer,
    permissions: {
      calls: callPermissions,
      spend: [{ limit: parseUnits(input.spendCapUsd1.toString(), 18), period: 'day', token: paymentToken }],
    },
    expiry: expirySeconds,
    register: true, // full public KeyStore registration — Altana-track checklist item
    chainId: BNB_TESTNET.chainId,
  })

  const sessionId = `altana_${randomUUID()}`
  liveSessions.set(sessionId, grant)

  logger.info(
    { sessionId, walletAddress: grant.walletAddress, expiry: expirySeconds, tx: grant.transactionHash },
    'altana: real scoped session granted (KeyStore-registered)',
  )

  return {
    id: sessionId,
    jobId: input.jobId,
    agentId: input.agentId,
    allowlist: input.allowlist,
    spendCapUsd1: input.spendCapUsd1,
    expiresAt: new Date(expirySeconds * 1000).toISOString(),
    revokedAt: null,
    keystoreTx: grant.transactionHash ?? null,
  }
}

export interface HireErc8183Result {
  escrowRef: string
  fundedTx: string | null
}

export interface HireErc8183Params {
  /** Real ERC-8004-registered seller/provider address — never fabricated. */
  provider: Address
  task: string
  /** Budget in $U (United Stables), human units (e.g. 5 = 5 $U). */
  budgetUsd1: number
  deadlineSeconds?: number
}

/**
 * Altana's ERC-8183 hiring helper — Altana-track bonus criterion. Wired to
 * the real SDK call. See file header: genuinely untested live this wave —
 * needs a real `provider` counterparty and $U balance, neither fabricated.
 * Callers MUST supply a real, already-known provider address; this
 * function does not invent one.
 */
export async function hireErc8183Agent(
  sessionId: string,
  params: HireErc8183Params,
): Promise<HireErc8183Result | null> {
  const session = liveSessions.get(sessionId)
  if (!session) {
    logger.warn({ sessionId }, 'altana.hireErc8183Agent: no live session for id — refusing')
    return null
  }
  const result = await sdkHireErc8183Agent(
    session,
    { provider: params.provider, task: params.task, budget: parseUnits(params.budgetUsd1.toString(), 18) },
    { network: BNB_TESTNET },
  )
  return {
    escrowRef: result.jobId.toString(),
    fundedTx: result.transactionHash ?? null,
  }
}

export async function revokeSession(
  sessionId: string,
): Promise<{ revokedAt: string; tx: string | null } | null> {
  const session = liveSessions.get(sessionId)
  if (!session) {
    logger.warn({ sessionId }, 'altana.revokeSession: no live session for id')
    return null
  }
  const client = getAltanaClient()
  const wallet = getAltanaWallet()
  const signer = getAltanaWalletSigner()

  const result = await client.revokeSession({ wallet, signer, session, chainId: BNB_TESTNET.chainId })
  liveSessions.delete(sessionId)

  logger.info({ sessionId, tx: result.transactionHash }, 'altana: real session revoked on-chain')

  return { revokedAt: new Date().toISOString(), tx: result.transactionHash ?? null }
}

/**
 * Plain-language Trust Panel sentence from an actual session config — never
 * from anything other than the session object itself (no paraphrasing of
 * agent-reported claims).
 */
export function permissionSentence(
  session: Pick<Session, 'allowlist' | 'spendCapUsd1' | 'expiresAt'>,
): string {
  const scope = session.allowlist.length > 0 ? session.allowlist.join(', ') : 'nothing yet'
  const expiry = new Date(session.expiresAt).toLocaleDateString()
  return `Can trade ${scope}, up to $${session.spendCapUsd1.toFixed(2)}/day, until ${expiry}.`
}

// Re-exported for callers that want to read job state directly (e.g. a
// future job-status poller) without duplicating SDK imports.
export { ERC8183_ADDRESSES, buildHireCalls, getErc8183Job }
