/**
 * apps/api/src/lib/altana-client.ts
 *
 * Shared Altana SDK client for the API process (INTEGRATION.md I6). Mirrors
 * lib/chain.ts's lazy-singleton pattern.
 *
 * Uses the REAL @altananetwork/sdk (no API key, no hosted backend — see
 * INTEGRATION.md I14/I6 correction) against BNB_TESTNET (BSC Chapel,
 * chainId 97) — the SDK's exported testnet chain config, confirmed from the
 * package source (`node_modules/@altananetwork/sdk/dist/config.js`):
 * keystore + account stack + relay all live on chain 97 as a standalone
 * testnet ecosystem (unlike Sepolia/Base Sepolia, which are keystore-only).
 *
 * The wallet used here is the bootstrap agent wallet from
 * ALTANA_WALLET_PRIVATE_KEY (apps/api/.env.altana-agent, gitignored,
 * generated by scripts/altana-live-proof.ts) — NOT KEEPER_ATTESTER_KEY, NOT
 * DEMO_AGENT_PRIVATE_KEY. A real per-marketplace-agent wallet registry (one
 * Altana wallet per listed agent) is a follow-up needing a DB table; this
 * wave wires the SDK correctly against one real wallet end-to-end.
 */
import { BNB_TESTNET, createClient, signerFromPrivateKey, type Client, type Signer, type Wallet } from '@altananetwork/sdk'
import type { Address, Hex } from 'viem'
import { env } from '../env.js'

let clientSingleton: Client | null = null

/** The Altana SDK client, configured for BNB Testnet (chain 97). */
export function getAltanaClient(): Client {
  if (!clientSingleton) {
    clientSingleton = createClient({ chains: [BNB_TESTNET] })
  }
  return clientSingleton
}

export { BNB_TESTNET }

/** Admin signer for the bootstrap Altana wallet (never logged). */
export function getAltanaWalletSigner(): Signer {
  if (!env.ALTANA_WALLET_PRIVATE_KEY) {
    throw new Error('altana-client: ALTANA_WALLET_PRIVATE_KEY not configured (apps/api/.env.altana-agent)')
  }
  return signerFromPrivateKey(env.ALTANA_WALLET_PRIVATE_KEY as Hex)
}

/** The bootstrap Altana wallet handle (address only — no key material). */
export function getAltanaWallet(): Wallet {
  if (!env.ALTANA_WALLET_ADDRESS) {
    throw new Error('altana-client: ALTANA_WALLET_ADDRESS not configured (apps/api/.env.altana-agent)')
  }
  return { address: env.ALTANA_WALLET_ADDRESS as Address }
}
