/**
 * apps/api/src/env.ts
 *
 * Single point of env-var access for the API. Every var here is documented
 * in docs/technical/INTEGRATION.md ("Environment variables" table) and
 * mirrored in the repo-root `.env.example` — that's the doc-contract this
 * file must never violate (CLAUDE.md §4 env discipline).
 *
 * Everything is OPTIONAL at the type level for Phase A: no external API keys
 * are provisioned this session (8004scan / Altana / TermiX / RPCs / DB), and
 * the API must still boot + serve /api/health without them. Services that
 * need a given var check for it themselves and report "unconfigured" rather
 * than throwing at import time.
 *
 * NEVER log KEEPER_ATTESTER_KEY, DEMO_AGENT_PRIVATE_KEY, or any private key
 * (CLAUDE.md §4). This file exposes them as values, not getters that log —
 * callers must not console.log them.
 *
 * DEMO_AGENT_PRIVATE_KEY lives in a SEPARATE gitignored file
 * (`.env.demo-agent`, mirrors packages/contracts/.env.chapel-deploy's
 * pattern) rather than the shared `.env` — loaded explicitly below since
 * `dotenv/config` only auto-loads `.env`. This is the self-hosted session
 * enforcement signer (services/session-enforcement.ts), NOT the
 * KEEPER_ATTESTER_KEY role — it only ever calls the access-control-free
 * ProofLedger.registerDecision, never attestOutcome.
 */
import 'dotenv/config'
import dotenv from 'dotenv'
import { z } from 'zod'

dotenv.config({ path: '.env.demo-agent' })
dotenv.config({ path: '.env.altana-agent' })

const EnvSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().positive().default(4000),

  // Postgres (Supabase) — cache/derived views only, never authoritative (ERD.md §1)
  DATABASE_URL: z.string().min(1).optional(),

  // 8004scan (AltLayer) — I2
  SCAN8004_API_KEY: z.string().min(1).optional(),
  SCAN8004_BASE_URL: z.string().url().default('https://api.8004scan.io'),

  // BSC RPC — I1/I3 chain reads/writes
  BSC_RPC_URL: z.string().url().optional(),
  BSC_TESTNET_RPC_URL: z.string().url().optional(),

  // ProofLedger (ours) — pinned at deploy time (SMART-CONTRACT.md)
  PROOFLEDGER_ADDRESS_MAINNET: z.string().min(1).optional(),
  PROOFLEDGER_ADDRESS_TESTNET: z.string().min(1).optional(),
  ERC8004_REGISTRY_ADDRESS: z.string().min(1).optional(),

  // Keeper's sole privileged secret — read here only so services can check
  // "is attestation configured", never printed/logged.
  KEEPER_ATTESTER_KEY: z.string().min(1).optional(),

  // Altana (I6) — sessions, Keystore, hireErc8183Agent. CORRECTED 2026-08-17:
  // the real @altananetwork/sdk needs NO API key / hosted backend (confirmed
  // against docs.altana.network + the published package itself — see
  // INTEGRATION.md I6/I14). ALTANA_API_KEY/ALTANA_BASE_URL below are dead
  // config kept only so nothing breaks if they're still set somewhere; the
  // real integration point is the wallet key pair below.
  ALTANA_API_KEY: z.string().min(1).optional(),
  ALTANA_BASE_URL: z.string().url().default('https://api.altana.network'),

  // Real Altana agent-owned wallet — self-custodial, generated by
  // scripts/altana-live-proof.ts, lives only in gitignored
  // apps/api/.env.altana-agent (mirrors DEMO_AGENT_PRIVATE_KEY's pattern).
  // This is the bootstrap wallet services/altana.ts uses this wave — a real
  // per-agent wallet registry (one Altana wallet per marketplace agent) is a
  // follow-up, not yet backed by a DB table (see INTEGRATION.md I6).
  ALTANA_WALLET_ADDRESS: z.string().min(1).optional(),
  ALTANA_WALLET_PRIVATE_KEY: z.string().min(1).optional(),

  // Dedicated Chapel gas sponsor for fresh per-job Altana wallets. Keep this
  // separate from the ProofLedger attester, demo-agent, and bootstrap keys.
  ALTANA_FUNDING_PRIVATE_KEY: z.string().min(1).optional(),

  // x402 / B402 (I5) — per-task payments, USD1 settlement
  X402_FACILITATOR_URL: z.string().url().optional(),
  PROTOCOL_FEE_BPS: z.coerce.number().int().nonnegative().default(300),

  // TermiX (I9)
  TERMIX_API_KEY: z.string().min(1).optional(),

  // Self-hosted session enforcement signer (INTEGRATION.md I6 honesty note) —
  // fresh dedicated demo-agent key, NOT the Altana SDK, NOT KEEPER_ATTESTER_KEY.
  // Public address may be logged; the private key must never be.
  DEMO_AGENT_ADDRESS: z.string().min(1).optional(),
  DEMO_AGENT_PRIVATE_KEY: z.string().min(1).optional(),

  // web origin, for CORS
  NEXT_PUBLIC_API_URL: z.string().url().optional(),
})

export type Env = z.infer<typeof EnvSchema>

function loadEnv(): Env {
  const parsed = EnvSchema.safeParse(process.env)
  if (!parsed.success) {
    // Env vars are all optional/defaulted by design (Phase A stub) — a parse
    // failure here means a *malformed* value (e.g. bad URL), not a missing
    // one. Fail loudly; this should never happen in CI/dev with .env.example.
    console.error('[env] invalid environment configuration:', parsed.error.flatten().fieldErrors)
    throw new Error('Invalid environment configuration — see stderr for field errors')
  }
  return parsed.data
}

export const env = loadEnv()

/** True once every var a given integration needs is present. Never true this session (Phase A). */
export const integrationConfigured = {
  database: Boolean(env.DATABASE_URL),
  scan8004: Boolean(env.SCAN8004_API_KEY),
  bscRpc: Boolean(env.BSC_RPC_URL),
  bscTestnetRpc: Boolean(env.BSC_TESTNET_RPC_URL),
  // Real @altananetwork/sdk needs no API key — readiness is "do we have a
  // wallet key to act with", not "is ALTANA_API_KEY set" (see comment above).
  altana: Boolean(env.ALTANA_WALLET_PRIVATE_KEY),
  keeperAttester: Boolean(env.KEEPER_ATTESTER_KEY),
  termix: Boolean(env.TERMIX_API_KEY),
  demoAgentSigner: Boolean(env.DEMO_AGENT_PRIVATE_KEY),
} as const
