/**
 * apps/api/scripts/altana-live-proof.ts
 *
 * ONE-OFF proof script (not part of the app runtime) — proves the real
 * @altananetwork/sdk end-to-end against real BSC Chapel testnet:
 *   1. generate a fresh Altana wallet (agent-owned key)
 *   2. fund it with a little tBNB from the existing deployer key
 *      (packages/contracts/.env.chapel-deploy — read via a scoped dotenv
 *      load, never printed)
 *   3. grant a real scoped session (allowlist = ProofLedger.registerDecision
 *      only, spend cap, expiry)
 *   4. execute a REAL registerDecision call on the live deployed ProofLedger
 *      THROUGH the session key (not the admin key) — proves session-scoped
 *      execution against our own contract, not a no-op transfer
 *   5. revoke the session for real
 *   6. attempt one more execute() through the revoked session — must fail
 *
 * Persists the generated wallet + session private keys to
 * apps/api/.env.altana-agent (gitignored, mirrors .env.demo-agent's
 * pattern) — NEVER printed to stdout.
 *
 * Run: cd apps/api && pnpm exec tsx scripts/altana-live-proof.ts
 */
import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import dotenv from 'dotenv'
import {
  BNB_TESTNET,
  createClient,
  signerFromPrivateKey,
} from '@altananetwork/sdk'
import {
  createPublicClient,
  createWalletClient,
  http,
  parseEther,
  type Hex,
} from 'viem'
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts'
import { bscTestnet } from 'viem/chains'
import { proofLedgerAbi } from '@agentdesk/sdk'

// ---------------------------------------------------------------------------
// Scoped env loads — deployer key stays in this process only, never logged.
// ---------------------------------------------------------------------------
const apiEnvPath = resolve(import.meta.dirname, '..', '.env')
const deployerEnvPath = resolve(import.meta.dirname, '..', '..', '..', 'packages', 'contracts', '.env.chapel-deploy')

const apiEnv = dotenv.parse(readFileSync(apiEnvPath, 'utf8'))
const deployerEnv = dotenv.parse(readFileSync(deployerEnvPath, 'utf8'))

const RPC_URL = apiEnv.BSC_TESTNET_RPC_URL
const PROOFLEDGER_ADDRESS = apiEnv.PROOFLEDGER_ADDRESS_TESTNET as `0x${string}`
const DEPLOYER_PRIVATE_KEY = deployerEnv.PRIVATE_KEY as Hex

if (!RPC_URL || !PROOFLEDGER_ADDRESS || !DEPLOYER_PRIVATE_KEY) {
  throw new Error('altana-live-proof: missing RPC_URL / PROOFLEDGER_ADDRESS / deployer key — check env files')
}

const publicClient = createPublicClient({ chain: bscTestnet, transport: http(RPC_URL) })
const deployerAccount = privateKeyToAccount(DEPLOYER_PRIVATE_KEY)
const deployerWalletClient = createWalletClient({
  chain: bscTestnet,
  account: deployerAccount,
  transport: http(RPC_URL),
})

function log(...args: unknown[]) {
  console.log('[altana-proof]', ...args)
}

async function main() {
  // 1. Fresh Altana wallet (agent-owned key) --------------------------------
  const walletPrivateKey = generatePrivateKey()
  const walletSigner = signerFromPrivateKey(walletPrivateKey)
  const client = createClient({ chains: [BNB_TESTNET] })
  const wallet = await client.createWallet({ signer: walletSigner })
  log('created Altana wallet (counterfactual, not yet on-chain):', wallet.address)

  // Persist the wallet key IMMEDIATELY — before any funding/spend — so a
  // failed later step (grantSession/execute) never strands recoverable
  // tBNB behind a lost in-memory-only key. Session key gets appended once
  // granted, further down.
  const outPath = resolve(import.meta.dirname, '..', '.env.altana-agent')
  writeFileSync(
    outPath,
    [
      `# apps/api/.env.altana-agent — GENERATED by scripts/altana-live-proof.ts, gitignored (matches .env.* in root .gitignore)`,
      `# Altana agent-owned wallet — self-custodial, generated ${new Date().toISOString()}`,
      `ALTANA_WALLET_ADDRESS=${wallet.address}`,
      `ALTANA_WALLET_PRIVATE_KEY=${walletPrivateKey}`,
      '',
    ].join('\n'),
    { mode: 0o600 },
  )
  log('wallet key persisted early to', outPath, '(gitignored)')

  // 2. Fund with a little tBNB from the deployer ----------------------------
  // Deployer was refunded to ~0.3 tBNB (2026-08-17) — plenty of headroom now,
  // so this run funds generously enough to cover a REAL register:true grant
  // (KeyStore registration fee) plus gas for grant+execute+revoke+the
  // deliberately-failing post-revoke execute attempt.
  const fundAmount = parseEther('0.02')
  log('funding wallet with', fundAmount.toString(), 'wei tBNB from deployer', deployerAccount.address)
  const fundTx = await deployerWalletClient.sendTransaction({
    to: wallet.address,
    value: fundAmount,
  })
  const fundReceipt = await publicClient.waitForTransactionReceipt({ hash: fundTx })
  log('funding tx:', fundTx, 'status:', fundReceipt.status, 'block:', fundReceipt.blockNumber.toString())

  const balance = await publicClient.getBalance({ address: wallet.address })
  log('wallet balance after funding:', balance.toString(), 'wei')

  // 3. Grant a real scoped session -------------------------------------------
  // Deployer now has plenty of headroom (~0.3 tBNB, refunded 2026-08-17) —
  // this run uses register:true so the session is genuinely registered in
  // the PUBLIC on-chain Keystore (not just enforced by the account contract),
  // ticking the real "Keystore-registered" Altana-track checklist box.
  const expiry = Math.floor(Date.now() / 1000) + 24 * 60 * 60 // 24h
  const grant = await client.grantSession({
    wallet,
    signer: walletSigner,
    permissions: {
      calls: [{ to: PROOFLEDGER_ADDRESS, signature: 'registerDecision(uint256,bytes32,uint64)' }],
      spend: [{ limit: parseEther('0.005'), period: 'day' }],
    },
    expiry,
    register: true,
  })
  log('session granted. publicKey:', grant.publicKey, 'expiry:', new Date(expiry * 1000).toISOString())
  log('grant transactionHash:', grant.transactionHash ?? '(none reported by relay)')

  // 4. Execute a REAL registerDecision call THROUGH the session -------------
  // IMPORTANT: `deadline` on the real deployed contract is `uint64`, not
  // `uint256` (see packages/contracts/src/ProofLedger.sol) — a wrong type
  // here silently produces the WRONG 4-byte selector, which the relay's
  // simulation reverts with an opaque "0x" (no matching function). Use the
  // real exported ABI (@agentdesk/sdk) instead of hand-rolling one, exactly
  // like session-enforcement.ts already does.
  const agentId = 1n
  const intentHash = ('0x' + '11'.repeat(32)) as Hex
  const deadline = BigInt(Math.floor(Date.now() / 1000) + 3600)

  const { encodeFunctionData } = await import('viem')
  const callData = encodeFunctionData({
    abi: proofLedgerAbi,
    functionName: 'registerDecision',
    args: [agentId, intentHash, deadline],
  })

  // (Admin-path diagnostic removed once root-caused — deployer balance is
  // too tight to spend on a non-essential extra tx. The earlier failure was
  // confirmed to be insufficient wallet balance for grantSession's KeyStore
  // registration fee, not a permissions/selector bug — see git history of
  // this file / final report for the trace.)
  log('executing registerDecision THROUGH the session key (not admin) on', PROOFLEDGER_ADDRESS)
  const execResult = await client.execute({
    session: grant,
    calls: { to: PROOFLEDGER_ADDRESS, data: callData },
  })
  log('execute result:', JSON.stringify(execResult))

  // Read back on-chain to confirm the decision was actually registered.
  if (execResult.transactionHash) {
    const receipt = await publicClient.waitForTransactionReceipt({ hash: execResult.transactionHash })
    log('on-chain receipt status:', receipt.status, 'block:', receipt.blockNumber.toString())
  }

  // 5. Revoke the session for real -------------------------------------------
  log('revoking session...')
  const revokeResult = await client.revokeSession({
    wallet,
    signer: walletSigner,
    session: grant,
  })
  log('revoke result:', JSON.stringify(revokeResult))
  if (revokeResult.transactionHash) {
    const receipt = await publicClient.waitForTransactionReceipt({ hash: revokeResult.transactionHash })
    log('revoke on-chain receipt status:', receipt.status, 'block:', receipt.blockNumber.toString())
  }

  // 6. Attempt one more execute() through the revoked session — must fail ----
  const intentHash2 = ('0x' + '22'.repeat(32)) as Hex
  const callData2 = encodeFunctionData({
    abi: proofLedgerAbi,
    functionName: 'registerDecision',
    args: [agentId, intentHash2, deadline],
  })
  try {
    const postRevokeResult = await client.execute({
      session: grant,
      calls: { to: PROOFLEDGER_ADDRESS, data: callData2 },
    })
    log('UNEXPECTED: post-revoke execute succeeded:', JSON.stringify(postRevokeResult))
  } catch (err) {
    log('EXPECTED: post-revoke execute refused:', err instanceof Error ? err.message : err)
  }

  // Append session details (never printed) ------------------------------------
  appendFileSync(
    outPath,
    [
      `# Session key used above — session was revoked as part of this proof run; kept for audit reference only.`,
      `ALTANA_SESSION_PUBLIC_KEY=${grant.publicKey}`,
      `ALTANA_SESSION_SIGNER_ADDRESS=${grant.signer.address}`,
      '',
    ].join('\n'),
  )
  log('session details appended to', outPath, '(gitignored — verify with `git check-ignore -v`)')

  log('=== SUMMARY (safe to share — no secrets) ===')
  log('Altana wallet address:', wallet.address)
  log('Funding tx:', fundTx)
  log('Session grant tx:', grant.transactionHash ?? '(relay did not report one)')
  log('Session execute (registerDecision) tx:', execResult.transactionHash ?? execResult.callsId)
  log('Session revoke tx:', revokeResult.transactionHash ?? revokeResult.callsId)
}

main().catch((err) => {
  console.error('[altana-proof] FAILED:', err)
  process.exitCode = 1
})
